language: java
jdk:
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master

install:
  - cd ./Zabbigot
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B