# It is used when you want to stop temporarily by maintenance etc.
# If it is false, it will not send.
Enable: true

# Use to monitor multiple servers.
# Sends the value specified here as an argument.
Identifier: "Minecraft"

# Example:
# Identifier: "Minecraft" -> "minecraft.tps[Minecraft]"
# Identifier: "Zabbigot" -> "minecraft.tps[Zabbigot]"

# 60s = 1min 
Period: 60

Zabbix:
  Server: "zabbix.example.com"
  Port: 10051
  Hostname: "MinecraftServer"